### github-action-variable-01.yml

name: Test Github Actions variable-01
on:
  push

env:
  DAY_OF_WEEK: Friday ### 전역변수

jobs:
  check-var:
    runs-on: ubuntu-latest
    env:
      MESSAGE: Hello ### 지역변수
    steps:
      - name: "It's Day!"
        run: echo "$MESSAGE, Today is $DAY_OF_WEEK!"
    
  
