### github-action-02.yml
name: Test GitHub Actions-02
run-name: Run GitHub Actions-02
on:
  ### push
  workflow_dispatch
jobs:
  Test-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: step-02
        run: |
          echo "Test Github Actions echos-02"
